Refactor: Delete store and unused code
jina-ai/dashboard pull request #169
Opened 2021-02-07 01:31 UTC by BastinJafari

2021-02-08 16:02 UTC, Roshanjossey commented
![image](https://user-images.githubusercontent.com/8488446/107245384-61b21500-6a2f-11eb-9d37-c85a97109e2a.png)

Percy caught something. @BastinJafari, could you check the elements in the footer? Not sure what it has to do with store though.

2021-02-08 17:37 UTC, BastinJafari commented
I deleted a lot of components that I thought wouldn't get used anymore. 
Regarding this display bug, I can't reproduce it.

2021-02-08 17:43 UTC, Roshanjossey requested changes
I think we shouldn't remove Hub routes and code associated with it. From what I understand, that use case is still needed

2021-02-08 17:43 UTC, Roshanjossey commented on src/index.tsx
> -let App;
I think we still need this. From what I understand, the usecase is to deploy standalone Hub. @imsergiy, could you confirm?

2021-02-08 17:43 UTC, Roshanjossey commented on src/layouts/index.ts
> +export { IconSidebar };
Same here.

2021-02-09 16:17 UTC, Roshanjossey approved these changes

2021-02-09 18:39 UTC, merged