Feat GitHub oauth 219
jina-ai/dashboard pull request #256
Opened 2021-03-11 14:04 UTC by BastinJafari

Basic reducer for logging in and logging out. Since we don't have a lambda function yet, the login page is broken and will throw an error

2021-03-11 14:07 UTC, deepankarm commented
@BastinJafari I'll create a new api gateway endpoint with github authorizer for this testing to unblock you tomorrow.

2021-04-15 09:28 UTC, Roshanjossey requested changes

2021-04-15 09:28 UTC, Roshanjossey commented on src/views/LogIn.tsx
> +    const parsed = queryString.parse(window.location.search)
```suggestion
    const queryParams = queryString.parse(window.location.search)
```

2021-04-15 09:28 UTC, Roshanjossey commented on src/services/github.ts
> +export function loginGithub(code: string) {
Could you write unit tests for these functions

2021-04-21 16:16 UTC, imsergiy approved these changes

2021-04-21 19:54 UTC, Roshanjossey approved these changes

2021-04-22 14:05 UTC, BastinJafari commented on src/redux/global/global.types.ts
> +  photos?: [{ value: string }]
Actually not!
Removed it

2021-04-23 12:51 UTC, merged